"""Build content/placement/vocab.json: the yes/no vocab test (DECISIONS 9, 43).

    uv run python scripts/build_placement.py

96 real words, 16 from each of 6 rank-quantile bands of the NIKL list, plus
24 pseudowords, shuffled with a fixed seed so the output is reproducible.
Pseudowords must be absent from the NIKL list and the local krdict index.
"""
import json
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.analyzer import lemmatize  # noqa: E402
from app.config import CONTENT_DIR, KRDICT_LOCAL_PATH, NIKL_VOCAB_PATH  # noqa: E402
from app.krdict.local import LocalDict  # noqa: E402
from app.nikl import parse  # noqa: E402

SEED = 20261003
BANDS = 6
PER_BAND = 16
TEST_POS = {"NNG", "VV", "VA", "MAG"}

# Written in-session (Claude): Korean-shaped, no dictionary entry.
PSEUDOWORDS = [
    "두림", "갈무치", "소담결", "퉁지", "하로개", "채름", "도롱개", "가르뭉", "너시래", "바스금",
    "감추르다", "몰구다", "쏘무리다", "다그리다", "졸기다", "흘미다", "부루치다", "사무르다",
    "산뜰하다", "무르릇하다", "떫적하다", "고슬막하다", "푸릇담하다", "너즈막하다",
]

OUT = CONTENT_DIR / "placement" / "vocab.json"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    words = parse(NIKL_VOCAB_PATH)
    listed = {w.lemma for w in words} | {w.nikl_word.rstrip("0123456789") for w in words}
    local = LocalDict(KRDICT_LOCAL_PATH)
    bad = [p for p in PSEUDOWORDS if p in listed or local.search(p)]
    if bad:
        sys.exit(f"pseudowords that are real words: {bad}")

    # Only words that surface as themselves in running text (no derived/split forms).
    pool = sorted((w for w in words if w.pos in TEST_POS and w.rank is not None
                   and lemmatize(w.lemma) == (w.lemma, w.pos)), key=lambda w: w.rank)
    rng = random.Random(SEED)
    items = []
    size = len(pool) / BANDS
    for b in range(BANDS):
        band = pool[round(b * size):round((b + 1) * size)]
        seen: set[str] = set()
        picks = [w for w in rng.sample(band, len(band)) if not (w.lemma in seen or seen.add(w.lemma))][:PER_BAND]
        for w in sorted(picks, key=lambda w: w.rank):
            items.append({"id": f"v-{w.lemma}-{w.pos}", "word": w.lemma, "real": True, "lemma": w.lemma,
                          "pos": w.pos, "rank": w.rank, "band": w.band, "quantile": b + 1})
    for p in PSEUDOWORDS:
        items.append({"id": f"p-{p}", "word": p, "real": False})
    rng.shuffle(items)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    doc = {"_note": "Generated by server/scripts/build_placement.py; do not edit by hand.",
           "seed": SEED, "pool_size": len(pool), "items": items}
    OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {len(items)} items from a pool of {len(pool)}")
    for b in range(BANDS):
        ranks = [i["rank"] for i in items if i.get("quantile") == b + 1]
        print(f"  band {b + 1}: ranks {min(ranks)}-{max(ranks)}")


if __name__ == "__main__":
    main()
