"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 08:46:22.866469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    op.create_table('grammar_point',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label_ko', sa.String(), nullable=False),
    sa.Column('ja_parallel', sa.String(), nullable=True),
    sa.Column('ja_diff_note', sa.Text(), nullable=True),
    sa.Column('htsk_lesson', sa.Integer(), nullable=True),
    sa.Column('kiwi_pattern', sa.JSON(), nullable=True),
    sa.Column('prereqs', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ingest_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexeme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('hanja', sa.String(), nullable=True),
    sa.Column('gloss_en', sa.Text(), nullable=False),
    sa.Column('gloss_ja', sa.Text(), nullable=True),
    sa.Column('gloss_source', sa.String(), nullable=False),
    sa.Column('freq_rank', sa.Integer(), nullable=True),
    sa.Column('freq_band', sa.String(), nullable=True),
    sa.Column('krdict_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lemma', 'pos')
    )
    op.create_table('context_sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('sentence_ko', sa.Text(), nullable=False),
    sa.Column('sentence_en', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('audio_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_sentence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_sentence_lexeme_id'), ['lexeme_id'], unique=False)

    op.create_table('episode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('title_ko', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('register_tags', sa.JSON(), nullable=False),
    sa.Column('target_grammar', sa.String(), nullable=True),
    sa.Column('new_lexemes', sa.JSON(), nullable=False),
    sa.Column('review_lexemes', sa.JSON(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_grammar'], ['grammar_point.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_episode_updated_at'), ['updated_at'], unique=False)

    op.create_table('grammar_state',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('fsrs_card', sa.JSON(), nullable=True),
    sa.Column('exposures', sa.Integer(), nullable=False),
    sa.Column('lookups', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['grammar_point.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('lexeme_state',
    sa.Column('lexeme_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('fsrs_card', sa.JSON(), nullable=True),
    sa.Column('exposures', sa.Integer(), nullable=False),
    sa.Column('lookups', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lexeme_id'], ['lexeme.id'], ),
    sa.PrimaryKeyConstraint('lexeme_id')
    )
    op.create_table('episode_paragraph',
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('ko', sa.Text(), nullable=False),
    sa.Column('en', sa.Text(), nullable=False),
    sa.Column('tokens', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('episode_id', 'idx')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('prompt_ko', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_idx', sa.Integer(), nullable=False),
    sa.Column('target_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_episode_id'), ['episode_id'], unique=False)

    op.create_table('story_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opened_in', sa.String(), nullable=False),
    sa.Column('closed_in', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['closed_in'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['opened_in'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_thread')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_episode_id'))

    op.drop_table('question')
    op.drop_table('episode_paragraph')
    op.drop_table('lexeme_state')
    op.drop_table('grammar_state')
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_updated_at'))
        batch_op.drop_index(batch_op.f('ix_episode_status'))

    op.drop_table('episode')
    with op.batch_alter_table('context_sentence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_sentence_lexeme_id'))

    op.drop_table('context_sentence')
    op.drop_table('lexeme')
    op.drop_table('ingest_doc')
    op.drop_table('grammar_point')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_ts'))

    op.drop_table('event')
    # ### end Alembic commands ###
